// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prrpkxpymithbynrfkqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBycnBreHB5bWl0aGJ5bnJma3FnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NTg4MjQsImV4cCI6MjA1NjMzNDgyNH0.f4w9RJX-Gp8qGSGEAXz6OuRVLuLIl6uGHH39AUUPXJQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);